export * from "./auth/register";
export * from "./product/get-product-by-slug";
export * from "./product/get-stock-by-slug";
export * from "./product/get-all-products";
export * from "./order/place-order";
export * from "./order/get-order-by-id";
export * from "./order/get-order-by-user";
export * from "./category/get-all-categories";
export * from "./order/actualizar-orden";
